version: "3"
services:
  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./ui:/usr/src/app

  service:
    restart: always
    container_name: service
    build:
      ./ui/service
    expose:
      - 5000
    volumes:
      - ./ui/service:/usr/src/app
    environment:
      - FLASK_ENV=production
